# Generated by Django 4.0.1 on 2022-02-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeingredient',
            name='amount',
            field=models.PositiveIntegerField(help_text='Требуемое количество для рецепта (целое число)', verbose_name='Количество'),
        ),
    ]
